language: ruby
rvm: 2.1.5
bundler_args: --without development production --deployment
addons:
  postgresql: 9.3
env:
  global:
    secure: b+caeL867fF5VvkxLOQ73R7J+3nO+KC8T/o5QuQwccL1knWN+2uWqZpla25CiPhVpuxxaJcOd4A+bErEb90zpoKTMH/DxBpN7IZII6ZAZtpkctyyiPUSB9BV0RV9gYsK6QF/y/E1qlBzEGiRO2e+qhP4dpXzuP9L9cW6Jwc6HM4=
before_script:
  - openssl aes-256-cbc -k $DEPLOY_KEY -in config/deploy_id_rsa_enc_travis -d -a -out config/deploy_id_rsa
  - chmod 600 config/deploy_id_rsa
  - ssh-add config/deploy_id_rsa
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
  - cp config/secrets.yml.example config/secrets.yml
script:
  - "[[ $TRAVIS_BRANCH = 'master' ]] && bundle exec cap staging deploy"
